# Tables for each base
table_mapping = {
    "i2b2": {
        "edsprod": {
            "visit": "i2b2_orbis_visit_dim",
            "documents": "i2b2_observation_fact_document",
            "patients": "i2b2_patient_dim",
            "icd10": "i2b2_arem_observation_fact_cim10",
            "procedure": "i2b2_arem_observation_fact_ccam",
            "cost": "i2b2_observation_fact_ghm",
            "care_site": "i2b2_observation_fact_ufr",
            "visit_detail": "i2b2_observation_fact_ufr",
            "biology": "i2b2_observation_fact_lab",
        },
        "other": {
            "visit": "i2b2_visit",
            "documents": "i2b2_observation_doc",
            "patients": "i2b2_patient",
            "icd10": "i2b2_observation_cim10",
            "procedure": "i2b2_observation_ccam",
            "cost": "i2b2_observation_ghm",
            "care_site": "i2b2_observation_ufr",
            "visit_detail": "i2b2_observation_ufr",
            "biology": "i2b2_observation_lab",
        },
    },
    "omop": {
        "all": {
            "visit": "visit_occurrence",
            "documents": "note",
            "patients": "person",
            "icd10": "condition_occurrence",
            "procedure": "procedure_occurrence",
            "cost": "cost",
            "care_site": "care_site",
            "visit_detail": "visit_detail",  # Not tested yet
            "biology": "observation",  # Not tested yet
        },
    },
}

# Mapping between i2b2 and OMOP
i2b2_renaming = {
    "documents": {
        "instance_num": "note_id",
        "start_date": "note_datetime",
        "concept_cd": "note_class_source_value",
        "encounter_num": "visit_occurrence_id",
        "patient_num": "person_id",
        "observation_blob": "note_text",
        "provider_id": "note_title",  # The title is not mentionned in i2b2 database
        "sourcesystem_cd": "cdm_source",
    },
    "patients": {
        "patient_num": "person_id",
        "birth_date": "birth_datetime",
        "death_date": "death_datetime",
        "sex_cd": "gender_source_value",
        "sourcesystem_cd": "cdm_source",
    },
    "visit": {
        "patient_num": "person_id",
        "encounter_num": "visit_occurrence_id",
        "location_cd": "care_site_id",
        "start_date": "visit_start_datetime",
        "end_date": "visit_end_datetime",
        "sourcesystem_cd": "cdm_source",
        "location_cd": "care_site_id",
        "type_visite": "visit_source_value",
        "mode_entree": "admitted_from_source_value",
        "mode_sortie": "discharge_to_source_value",
    },
    "icd10": {
        "patient_num": "person_id",
        "encounter_num": "visit_occurrence_id",
        "instance_num": "condition_occurrence_id",
        "start_date": "condition_start_datetime",
        "concept_cd": "condition_source_value",
        "tval_char": "condition_status_source_value",
        "sourcesystem_cd": "cdm_source",
    },
    "procedure": {
        "patient_num": "person_id",
        "encounter_num": "visit_occurrence_id",
        "instance_num": "procedure_occurrence_id",
        "start_date": "procedure_start_datetime",
        "concept_cd": "procedure_source_value",
        "sourcesystem_cd": "cdm_source",
    },
    "cost": {
        "patient_num": "person_id",
        "encounter_num": "visit_occurrence_id",
        "instance_num": "drg_source_concept_id",
        "start_date": "incurred_datetime",
        "concept_cd": "concept_cd",
        "sourcesystem_cd": "cdm_source",
    },
    "care_site": {
        "location_cd": "care_site_source_value",
        "encounter_num": "visit_occurrence_id",
    },
    "visit_detail": {
        "location_cd": "care_site_id",
        "encounter_num": "visit_occurrence_id",
        "start_date": "ufr_start_datetime",
        "end_date": "ufr_end_datetime",
        "sourcesystem_cd": "cdm_source",
    },
    "biology": {
        "patient_num": "person_id",
        "encounter_num": "visit_occurrence_id",
        "instance_num": "biology_occurrence_id",
        "start_date": "biology_start_datetime",
        "concept_cd": "biology_source_value",
        "sourcesystem_cd": "cdm_source",
        "nval_num": "biology_status_source_value",
    },
}


visit_type_mapping = {
    "I": "Hosp",
    "II": "Incomp",
    "U": "Urg",
    "O": "Ext",
}


mode_entree_mapping = {
    "1-DIRECT": "01",
    "1-CONS-HOP": "02",
    "1-ACC": "03",
    "2-URG": "04",
    "0-TRSF-MCO-INT": "05",
    "0-TRSF-MCO-INT-APHP": "06",
    "0-TRSF-SSR-INT": "07",
    "0-TRSF-SSR-INT-APHP": "08",
    "0-TRSF-SLD-INT": "09",
    "0-TRSF-SLD-INT-APHP": "10",
    "0-TRSF-PSY-INT": "11",
    "0-TRSF-PSY-INT-APHP": "12",
    "0-TRSF-HAD-INT": "13",
    "0-TRSF-HAD-INT-APHP": "14",
    "3-TRSF-MCO-EXT-APHP": "15",
    "3-TRSF-SSR-EXT-APHP": "16",
    "3-TRSF-SLD-EXT-APHP": "17",
    "3-TRSF-PSY-EXT-APHP": "18",
    "9-TRSF-NON-SANI": "27",
    "2-URG-ACC": "28",
    "0-TRSF-REA-INT-APHP": "29",
    "3-TRSF-REA-EXT-APHP": "30",
    "II": "Non Renseigné",
    "UT5": "Non Renseigné",
}


mode_sortie_mapping = {
    "1-DOMI": "01",
    "1-CLOT": "02",
    "6-DC": "03",
    "4-MCO-INT": "04",
    "2-SSR-INT": "05",
    "3-SLD-INT": "06",
    "A-PSY-INT": "07",
    "7-MCO": "08",
    "2-SSR": "09",
    "3-SLD": "10",
    "A-PSY": "11",
    "A-HAD": "12",
    "8-TRSF-NON-SANI": "19",
    "UT1": "20",
    "UT2": "21",
    "UT3": "22",
    "UT4": "23",
    "UT5": "24",
    "UN1": "25",
    "UN2": "26",
    "UN3": "27",
    "M": "Non Renseigné",
}

sex_cd_mapping = {"W": "f", "M": "m"}


dict_hospitals = {
    "care_site_name_long": {
        "032": "JVR - HOPITAL JEAN VERDIER",
        "095": "AVC - HOPITAL AVICENNE",
        "069": "RMB - HOPITAL RENE MURET - BIGOTTINI",
        "076": "SLS - HOPITAL SAINT LOUIS",
        "047": "LRB - GH LARIBOISIERE FERNAND WIDAL",
        "005": "BJN - HOPITAL BEAUJON",
        "033": "BRT - HOPITAL BRETONNEAU",
        "011": "BCH - HOPITAL BICHAT",
        "053": "LMR - HOPITAL LOUIS MOURIER",
        "066": "PSL - GROUPE HOSPITALIER PITIE-LA SALPETRIERE",
        "042": "CFX - GH CHARLES FOIX-JEAN ROSTAND",
        "072": "RTH - HOPITAL ROTHSCHILD",
        "049": "LRG - HOPITAL DE LA ROCHE-GUYON",
        "087": "TNN - HOPITAL TENON",
        "073": "SAT - HOPITAL SAINT ANTOINE",
        "088": "TRS - GH ARMAND TROUSSEAU-LA ROCHE GUYON",
        "028": "ABC - HOPITAL ANTOINE BECLERE",
        "096": "PBR - HOPITAL PAUL BROUSSE",
        "010": "BCT - HOPITAL DE BICETRE",
        "044": "JFR - GROUPE HOSPITALIER JOFFRE DUPUYTREN",
        "036": "GCL - HOPITAL GEORGES CLEMENCEAU",
        "029": "ERX - HOPITAL EMILE ROUX",
        "026": "HMN - GH A.CHENEVIER-H.MONDOR",
        "021": "CCH - GH COCHIN SAINT VINCENT DE PAUL",
        "041": "HTD - HOTEL-DIEU DE PARIS",
        "016": "BRC - GH BROCA-LA ROCHEFOUCAULD-LA COLLEGIALE",
        "022": "CCL - HOPITAL CORENTIN CELTON",
        "090": "VGR - HOPITAL DE VAUGIRARD-GABRIEL PALLEZ",
        "075": "BRS - GH BROUSSAIS-HEGP",
        "009": "BRK - HOPITAL MARITIME",
        "068": "RPC - GH RAYMOND POINCARE-BERCK",
        "014": "APR - HOPITAL AMBROISE PARE",
        "079": "SPR - HOPITAL STE PERINE",
        "038": "HND - HOPITAL MARIN",
        "061": "NCK - GROUPE HOSPITAL.NECKER ENFANTS MALADES",
        "064": "VPD - HOPITAL PAUL DOUMER",
        "070": "RDB - HOPITAL ROBERT DEBRE",
        "084": "SSL - HOPITAL SAN SALVADOUR",
        "099": "HAD - HOSPITALISATION A DOMICILE",
        "INC": "Inconnu",
    },
    "cd_gh": {
        "032": "G01",
        "095": "G01",
        "069": "G01",
        "076": "G02",
        "047": "G02",
        "005": "G03",
        "033": "G03",
        "011": "G03",
        "053": "G03",
        "066": "G04",
        "042": "G04",
        "072": "G06",
        "049": "G06",
        "087": "G06",
        "073": "G06",
        "088": "G06",
        "028": "G07",
        "096": "G07",
        "010": "G07",
        "044": "G08",
        "036": "G08",
        "029": "G08",
        "026": "G08",
        "021": "G12",
        "041": "G12",
        "016": "G12",
        "022": "G18",
        "090": "G18",
        "075": "G18",
        "009": "G24",
        "068": "G24",
        "014": "G24",
        "079": "G24",
        "038": "H38",
        "061": "H61",
        "064": "H64",
        "070": "H70",
        "084": "H84",
        "099": "H99",
        "INC": "INCONNU",
    },
    "lib_gh": {
        "032": "AVC JVR RMB - Hôpitaux universitaires Paris-Seine-Saint-Denis",
        "095": "AVC JVR RMB - Hôpitaux universitaires Paris-Seine-Saint-Denis",
        "069": "AVC JVR RMB - Hôpitaux universitaires Paris-Seine-Saint-Denis",
        "076": "LRB SLS - Groupe Hospitalier Saint-Louis Lariboisière Fernand-Widal",
        "047": "LRB SLS - Groupe Hospitalier Saint-Louis Lariboisière Fernand-Widal",
        "005": "BCH BJN LMR BRT CRC - Hôpitaux universitaires Paris Nord Val de Seine",
        "033": "BCH BJN LMR BRT CRC - Hôpitaux universitaires Paris Nord Val de Seine",
        "011": "BCH BJN LMR BRT CRC - Hôpitaux universitaires Paris Nord Val de Seine",
        "053": "BCH BJN LMR BRT CRC - Hôpitaux universitaires Paris Nord Val de Seine",
        "066": "PSL CFX - Groupe Hospitalier La Pitié Salpêtrière-Charles Foix",
        "042": "PSL CFX - Groupe Hospitalier La Pitié Salpêtrière-Charles Foix",
        "072": "SAT TNN TRS LRG RTH - Hôpitaux universitaires Est Parisien",
        "049": "SAT TNN TRS LRG RTH - Hôpitaux universitaires Est Parisien",
        "087": "SAT TNN TRS LRG RTH - Hôpitaux universitaires Est Parisien",
        "073": "SAT TNN TRS LRG RTH - Hôpitaux universitaires Est Parisien",
        "088": "SAT TNN TRS LRG RTH - Hôpitaux universitaires Est Parisien",
        "028": "ABC BCT PBR - Hôpitaux universitaires Paris-Sud",
        "096": "ABC BCT PBR - Hôpitaux universitaires Paris-Sud",
        "010": "ABC BCT PBR - Hôpitaux universitaires Paris-Sud",
        "044": "ACH HMN ERX GCL JFR - Groupe Hospitalier Henri Mondor",
        "036": "ACH HMN ERX GCL JFR - Groupe Hospitalier Henri Mondor",
        "029": "ACH HMN ERX GCL JFR - Groupe Hospitalier Henri Mondor",
        "026": "ACH HMN ERX GCL JFR - Groupe Hospitalier Henri Mondor",
        "021": "CCH HTD SVP BRC - Hôpitaux universitaires Paris Centre",
        "041": "CCH HTD SVP BRC - Hôpitaux universitaires Paris Centre",
        "016": "CCH HTD SVP BRC - Hôpitaux universitaires Paris Centre",
        "022": "BRS EGP CCL VGR - Hôpitaux Universitaires Paris-Ouest",
        "090": "BRS EGP CCL VGR - Hôpitaux Universitaires Paris-Ouest",
        "075": "BRS EGP CCL VGR - Hôpitaux Universitaires Paris-Ouest",
        "009": "APR RPC BRK SPR - Hôpitaux universitaires Paris Ile-de-France Ouest",
        "068": "APR RPC BRK SPR - Hôpitaux universitaires Paris Ile-de-France Ouest",
        "014": "APR RPC BRK SPR - Hôpitaux universitaires Paris Ile-de-France Ouest",
        "079": "APR RPC BRK SPR - Hôpitaux universitaires Paris Ile-de-France Ouest",
        "038": "HND - Hôpital Marin de Hendaye",
        "061": "NCK - Hôpital universitaire Necker-Enfants malades",
        "064": "VPD - null",
        "070": "RDB - Hôpital universitaire Robert-Debré",
        "084": "SSL - Hôpital San Salvadour",
        "099": "HAD - null",
        "INC": "Inconnu",
    },
    "lib_court_gh": {
        "032": "AVC JVR RMB",
        "095": "AVC JVR RMB",
        "069": "AVC JVR RMB",
        "076": "LRB SLS",
        "047": "LRB SLS",
        "005": "BCH BJN LMR BRT CRC",
        "033": "BCH BJN LMR BRT CRC",
        "011": "BCH BJN LMR BRT CRC",
        "053": "BCH BJN LMR BRT CRC",
        "066": "PSL CFX",
        "042": "PSL CFX",
        "072": "SAT TNN TRS LRG RTH",
        "049": "SAT TNN TRS LRG RTH",
        "087": "SAT TNN TRS LRG RTH",
        "073": "SAT TNN TRS LRG RTH",
        "088": "SAT TNN TRS LRG RTH",
        "028": "ABC BCT PBR",
        "096": "ABC BCT PBR",
        "010": "ABC BCT PBR",
        "044": "ACH HMN ERX GCL JFR",
        "036": "ACH HMN ERX GCL JFR",
        "029": "ACH HMN ERX GCL JFR",
        "026": "ACH HMN ERX GCL JFR",
        "021": "CCH HTD SVP BRC",
        "041": "CCH HTD SVP BRC",
        "016": "CCH HTD SVP BRC",
        "022": "BRS EGP CCL VGR",
        "090": "BRS EGP CCL VGR",
        "075": "BRS EGP CCL VGR",
        "009": "APR RPC BRK SPR",
        "068": "APR RPC BRK SPR",
        "014": "APR RPC BRK SPR",
        "079": "APR RPC BRK SPR",
        "038": "HND",
        "061": "NCK",
        "064": "VPD",
        "070": "RDB",
        "084": "SSL",
        "099": "HAD",
        "INC": None,
    },
    "cd_long_gh": {
        "032": "HUPSSD",
        "095": "HUPSSD",
        "069": "HUPSSD",
        "076": "LRB-SLS",
        "047": "LRB-SLS",
        "005": "HUPNVS",
        "033": "HUPNVS",
        "011": "HUPNVS",
        "053": "HUPNVS",
        "066": "PSL-CFX",
        "042": "PSL-CFX",
        "072": "HUEP",
        "049": "HUEP",
        "087": "HUEP",
        "073": "HUEP",
        "088": "HUEP",
        "028": "HUPS",
        "096": "HUPS",
        "010": "HUPS",
        "044": "HMN",
        "036": "HMN",
        "029": "HMN",
        "026": "HMN",
        "021": "HUPC",
        "041": "HUPC",
        "016": "HUPC",
        "022": "HUPO",
        "090": "HUPO",
        "075": "HUPO",
        "009": "HUPIFO",
        "068": "HUPIFO",
        "014": "HUPIFO",
        "079": "HUPIFO",
        "038": None,
        "061": "NCK",
        "064": None,
        "070": "RDB",
        "084": None,
        "099": None,
        "INC": None,
    },
    "care_site_name": {
        "014": "APR",
        "028": "ABC",
        "095": "AVC",
        "005": "BJN",
        "009": "BRK",
        "010": "BCT",
        "011": "BCH",
        "033": "BRT",
        "016": "BRC",
        "042": "CFX",
        "021": "CCH",
        "022": "CCL",
        "029": "ERX",
        "036": "GCL",
        "075": "EGC",
        "038": "HND",
        "026": "HMN",
        "099": "HAD",
        "041": "HTD",
        "032": "JVR",
        "044": "JFR",
        "047": "LRB",
        "049": "LRG",
        "053": "LMR",
        "061": "NCK",
        "096": "PBR",
        "066": "PSL",
        "068": "RPC",
        "069": "RMB",
        "070": "RDB",
        "072": "RTH",
        "073": "SAT",
        "079": "SPR",
        "076": "SLS",
        "084": "SSL",
        "087": "TNN",
        "088": "TRS",
        "090": "VGR",
        "064": "VPD",
        "INC": "INC",
    },
}


diagnostic_types_ref = {"DP": 1, "DR": 2, "DAS": 3}
